import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ShoppingBag,User,Search,ArrowRight,Menu,X,Package,Wallet,Users,Boxes,BarChart3,Settings,ShieldCheck,LogOut,Plus,Trash2,Upload,RefreshCw} from 'lucide-react';
import {supabase,configured} from './supabase';
import './style.css';

const fallback=[
 {id:'demo1',name:'Terra Woven Bag',brand:'Independent Artisan',price:118,img:'/products/bag-brown.jpg',stock:4},
 {id:'demo2',name:'Midnight Woven Bag',brand:'Independent Artisan',price:126,img:'/products/bag-blue.jpg',stock:3},
 {id:'demo3',name:'Signature Handwoven',brand:'Independent Artisan',price:132,img:'/products/bag-detail.jpg',stock:2},
];
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0));
function App(){
 const [cart,setCart]=useState([]),[admin,setAdmin]=useState(false),[menu,setMenu]=useState(false),[authOpen,setAuthOpen]=useState(false),[user,setUser]=useState(null),[profile,setProfile]=useState(null),[products,setProducts]=useState(fallback);
 useEffect(()=>{const fn=()=>document.documentElement.style.setProperty('--scroll',window.scrollY+'px');addEventListener('scroll',fn);return()=>removeEventListener('scroll',fn)},[]);
 useEffect(()=>{if(!supabase)return; supabase.auth.getSession().then(({data})=>setUser(data.session?.user||null)); const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user||null)); return()=>l.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!user||!supabase){setProfile(null);return} supabase.from('profiles').select('*').eq('id',user.id).single().then(({data})=>setProfile(data))},[user]);
 useEffect(()=>{loadProducts()},[]);
 async function loadProducts(){if(!supabase)return; const {data}=await supabase.from('products').select('id,name,price,sku,brand:brands(name),product_media(url,sort_order),product_stock(stock)').eq('active',true).order('created_at',{ascending:false}); if(data?.length)setProducts(data.map(p=>({...p,brand:p.brand?.name||'Artisan',img:p.product_media?.sort((a,b)=>a.sort_order-b.sort_order)?.[0]?.url||'/products/bag-brown.jpg',stock:p.product_stock?.[0]?.stock??0})));}
 const isAdmin=['admin','super_admin'].includes(profile?.role);
 if(admin&&isAdmin)return <Admin back={()=>setAdmin(false)} user={user}/>;
 return <div><header><button className="icon mobile" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><div className="logo">KARIA</div><nav className={menu?'open':''}><a href="#shop">SHOP</a><a href="#story">OUR STORY</a><a href="#brands">BRANDS</a><a href="#contact">CONTACT</a></nav><div className="actions"><Search/><button className="plain" onClick={()=>setAuthOpen(true)}><User/></button><button className="bag"><ShoppingBag/><b>{cart.length}</b></button></div></header>
 <main><section className="hero"><div className="heroCopy"><div className="eyebrow">HANDCRAFTED • ONE PIECE AT A TIME</div><h1>Made by hand.<br/><i>Made to be yours.</i></h1><p>Distinctive bags shaped slowly by skilled hands, thoughtful materials and individual stories.</p><a href="#shop" className="cta">Explore the collection <ArrowRight/></a></div><div className="stage"><div className="halo"></div><img src="/products/bag-brown.jpg" className="heroBag"/><span className="float f1">HANDWOVEN</span><span className="float f2">LIMITED PIECES</span></div><div className="scrollHint">SCROLL TO DISCOVER ↓</div></section>
 <section className="cinema" id="story"><div className="cinemaImg"><img src="/products/bag-blue.jpg"/></div><div><span>01 — THE CRAFT</span><h2>Texture tells<br/>the story.</h2><p>Every KARIA selection celebrates the identity of its maker. KARIA is the destination; each artisan brand keeps its own name, logo and story.</p></div></section>
 <section id="shop" className="shop"><div className="sectionHead"><div><span>THE COLLECTION</span><h2>Objects with a soul.</h2></div><button onClick={loadProducts}>Refresh collection →</button></div><div className="grid">{products.map(p=><article key={p.id}><div className="productImg"><img src={p.img}/><button disabled={p.stock<=0} onClick={()=>setCart(c=>[...c,p])}>{p.stock>0?'+ ADD TO BAG':'SOLD OUT'}</button></div><small>{p.brand}</small><h3>{p.name}</h3><div className="price">{money(p.price)} <span>{p.stock} available</span></div></article>)}</div></section>
 <section className="manifesto"><span>KARIA</span><h2>Handmade is not a trend.<br/>It is a way of making things matter.</h2><video src="/products/bag-video.mp4" muted autoPlay loop playsInline/></section></main>
 <footer><div className="logo">KARIA</div><p>Handcrafted bags & accessories.</p>{isAdmin&&<button className="adminLink" onClick={()=>setAdmin(true)}>Open Admin</button>}<small>© 2026 KARIA</small></footer>
 {authOpen&&<AuthModal user={user} profile={profile} close={()=>setAuthOpen(false)} admin={()=>{setAuthOpen(false);setAdmin(true)}}/>}</div>
}
function AuthModal({user,profile,close,admin}){const [mode,setMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[msg,setMsg]=useState(''); async function submit(e){e.preventDefault();if(!supabase)return setMsg('Supabase is not configured.');setMsg('Working…');let r=mode==='signup'?await supabase.auth.signUp({email,password,options:{data:{full_name:name}}}):await supabase.auth.signInWithPassword({email,password});setMsg(r.error?r.error.message:(mode==='signup'?'Account created. Check your email if confirmation is enabled.':'Signed in.'));} async function out(){await supabase.auth.signOut();close()} return <div className="modal"><div className="modalCard"><button className="close" onClick={close}><X/></button><div className="logo">KARIA</div>{user?<><h2>My account</h2><p>{user.email}</p><p>Role: <b>{profile?.role||'customer'}</b></p>{['admin','super_admin'].includes(profile?.role)&&<button className="primary" onClick={admin}>Open Admin</button>}<button className="secondary" onClick={out}><LogOut/> Sign out</button></>:<><h2>{mode==='login'?'Welcome back':'Create account'}</h2><form onSubmit={submit}>{mode==='signup'&&<input placeholder="Full name" value={name} onChange={e=>setName(e.target.value)} required/>}<input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" minLength="6" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/><button className="primary">{mode==='login'?'Sign in':'Create account'}</button></form><button className="linkBtn" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Create a new account':'I already have an account'}</button><p className="status">{msg}</p></>}</div></div>}
function Admin({back,user}){const [tab,setTab]=useState('Dashboard'),[products,setProducts]=useState([]),[brands,setBrands]=useState([]),[moves,setMoves]=useState([]),[orders,setOrders]=useState([]),[partners,setPartners]=useState([]),[expenses,setExpenses]=useState([]),[loading,setLoading]=useState(false);async function refresh(){if(!supabase)return;setLoading(true);const [p,b,m,o,pa,e]=await Promise.all([supabase.from('products').select('*,brand:brands(name),product_media(url),product_stock(stock)').order('created_at',{ascending:false}),supabase.from('brands').select('*').order('name'),supabase.from('inventory_movements').select('*,product:products(name,sku)').order('created_at',{ascending:false}).limit(50),supabase.from('orders').select('*').order('created_at',{ascending:false}).limit(50),supabase.from('partners').select('*'),supabase.from('expenses').select('*').order('expense_date',{ascending:false}).limit(50)]);setProducts(p.data||[]);setBrands(b.data||[]);setMoves(m.data||[]);setOrders(o.data||[]);setPartners(pa.data||[]);setExpenses(e.data||[]);setLoading(false)}useEffect(()=>{refresh()},[]);const revenue=orders.filter(x=>['paid','processing','shipped','delivered'].includes(x.status)).reduce((s,x)=>s+Number(x.subtotal||0),0),inv=products.reduce((s,x)=>s+(x.product_stock?.[0]?.stock||0),0),expenseTotal=expenses.reduce((s,x)=>s+Number(x.amount||0),0);const menu=[['Dashboard',BarChart3],['Orders',ShoppingBag],['Products',Package],['Brands',ShieldCheck],['Inventory',Boxes],['Production',Settings],['Customers',Users],['Accounting',Wallet],['Reports',BarChart3],['Admin users',Users]];return <div className="admin"><aside><div className="logo">KARIA</div><small>ADMINISTRATION</small>{menu.map(([x,I])=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}><I/>{x}</button>)}<button onClick={back}>← Storefront</button></aside><section className="adminMain"><div className="adminTop"><div><small>{tab.toUpperCase()}</small><h1>{tab}</h1></div><button className="secondary" onClick={refresh}><RefreshCw/> {loading?'Loading…':'Refresh'}</button></div>{tab==='Dashboard'&&<Dashboard revenue={revenue} orders={orders.length} inv={inv} profit={revenue-expenseTotal} partners={partners}/>} {tab==='Products'&&<Products products={products} brands={brands} refresh={refresh}/>} {tab==='Brands'&&<Brands brands={brands} refresh={refresh}/>} {tab==='Inventory'&&<Inventory products={products} moves={moves} refresh={refresh}/>} {tab==='Orders'&&<Orders orders={orders}/>} {tab==='Accounting'&&<Accounting expenses={expenses} refresh={refresh}/>} {!['Dashboard','Products','Brands','Inventory','Orders','Accounting'].includes(tab)&&<div className="panel"><h2>{tab}</h2><p>This module is connected to the KARIA database foundation and ready for the next operational data.</p></div>}</section></div>}
function Dashboard({revenue,orders,inv,profit,partners}){return <><div className="cards">{[['Revenue',money(revenue),Wallet],['Orders',orders,ShoppingBag],['Inventory',inv,Boxes],['Net result',money(profit),BarChart3]].map(([a,b,I])=><div key={a}><I/><small>{a}</small><strong>{b}</strong><em>Live from Supabase</em></div>)}</div><div className="adminGrid"><div className="panel"><h2>Ownership</h2>{partners.map(p=><div className="ownerRow" key={p.id}><b>{p.display_name}</b><span>{p.ownership_percent}%</span></div>)}</div><div className="panel"><h2>Accounting engine</h2><p>Orders → payment → sales → tax liability → fees → COGS → inventory → reports.</p><div className="flow">SALE → INVENTORY → LEDGER → REPORTS</div></div></div></>}
function Products({products,brands,refresh}){const [f,setF]=useState({name:'',sku:'',price:'',cost:'',brand_id:''}),[file,setFile]=useState(null),[msg,setMsg]=useState('');async function save(e){e.preventDefault();setMsg('Saving…');const slug=(f.name+'-'+Date.now()).toLowerCase().replace(/[^a-z0-9]+/g,'-');const {data:p,error}=await supabase.from('products').insert({name:f.name,slug,sku:f.sku,price:Number(f.price),unit_cost:Number(f.cost||0),brand_id:f.brand_id||null}).select().single();if(error)return setMsg(error.message);if(file){const path=`${p.id}/${Date.now()}-${file.name.replace(/\s+/g,'-')}`;const up=await supabase.storage.from('product-media').upload(path,file);if(!up.error){const {data:u}=supabase.storage.from('product-media').getPublicUrl(path);await supabase.from('product_media').insert({product_id:p.id,url:u.publicUrl})}}setF({name:'',sku:'',price:'',cost:'',brand_id:''});setFile(null);setMsg('Product created.');refresh()}async function del(id){if(confirm('Delete this product?')){await supabase.from('products').delete().eq('id',id);refresh()}}return <><div className="panel"><h2>Add product</h2><form className="formGrid" onSubmit={save}><input placeholder="Product name" value={f.name} onChange={e=>setF({...f,name:e.target.value})} required/><input placeholder="SKU" value={f.sku} onChange={e=>setF({...f,sku:e.target.value})} required/><input type="number" step=".01" placeholder="Price" value={f.price} onChange={e=>setF({...f,price:e.target.value})} required/><input type="number" step=".01" placeholder="Unit cost" value={f.cost} onChange={e=>setF({...f,cost:e.target.value})}/><select value={f.brand_id} onChange={e=>setF({...f,brand_id:e.target.value})}><option value="">Select brand</option>{brands.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select><label className="upload"><Upload/> Product photo<input type="file" accept="image/*" onChange={e=>setFile(e.target.files[0])}/></label><button className="primary"><Plus/> Create product</button></form><p className="status">{msg}</p></div><div className="panel tableWrap"><table><thead><tr><th>Photo</th><th>Product</th><th>Brand</th><th>SKU</th><th>Price</th><th>Cost</th><th>Stock</th><th></th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td>{p.product_media?.[0]?.url&&<img className="thumb" src={p.product_media[0].url}/>}</td><td>{p.name}</td><td>{p.brand?.name||'—'}</td><td>{p.sku}</td><td>{money(p.price)}</td><td>{money(p.unit_cost)}</td><td>{p.product_stock?.[0]?.stock||0}</td><td><button className="danger" onClick={()=>del(p.id)}><Trash2/></button></td></tr>)}</tbody></table></div></>}
function Brands({brands,refresh}){const [name,setName]=useState('');async function add(e){e.preventDefault();const slug=(name+'-'+Date.now()).toLowerCase().replace(/[^a-z0-9]+/g,'-');await supabase.from('brands').insert({name,slug});setName('');refresh()}return <div className="panel"><h2>Product brands</h2><form className="inlineForm" onSubmit={add}><input placeholder="Brand name" value={name} onChange={e=>setName(e.target.value)} required/><button className="primary"><Plus/> Add brand</button></form>{brands.map(b=><div className="ownerRow" key={b.id}><b>{b.name}</b><span>{b.active?'Active':'Inactive'}</span></div>)}</div>}
function Inventory({products,moves,refresh}){const [pid,setPid]=useState(''),[qty,setQty]=useState(''),[kind,setKind]=useState('IN'),[note,setNote]=useState('');async function post(e){e.preventDefault();await supabase.from('inventory_movements').insert({product_id:pid,qty:Number(qty),movement_type:kind,note});setQty('');setNote('');refresh()}return <><div className="panel"><h2>Inventory movement</h2><form className="formGrid" onSubmit={post}><select value={pid} onChange={e=>setPid(e.target.value)} required><option value="">Product</option>{products.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><select value={kind} onChange={e=>setKind(e.target.value)}><option>IN</option><option>OUT</option><option>RETURN</option><option>ADJUST</option><option>PRODUCTION_IN</option></select><input type="number" min="1" placeholder="Quantity" value={qty} onChange={e=>setQty(e.target.value)} required/><input placeholder="Reason / note" value={note} onChange={e=>setNote(e.target.value)}/><button className="primary">Post movement</button></form></div><div className="panel tableWrap"><table><thead><tr><th>Date</th><th>Product</th><th>Type</th><th>Qty</th><th>Note</th></tr></thead><tbody>{moves.map(m=><tr key={m.id}><td>{new Date(m.created_at).toLocaleDateString()}</td><td>{m.product?.name}</td><td>{m.movement_type}</td><td>{m.qty}</td><td>{m.note}</td></tr>)}</tbody></table></div></>}
function Orders({orders}){return <div className="panel tableWrap"><table><thead><tr><th>Order</th><th>Email</th><th>Status</th><th>Total</th><th>Date</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>#{o.order_number}</td><td>{o.email}</td><td>{o.status}</td><td>{money(o.total)}</td><td>{new Date(o.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div>}
function Accounting({expenses,refresh}){const [f,setF]=useState({vendor:'',category:'',description:'',amount:''});async function add(e){e.preventDefault();await supabase.from('expenses').insert({...f,amount:Number(f.amount)});setF({vendor:'',category:'',description:'',amount:''});refresh()}return <><div className="panel"><h2>Record expense</h2><form className="formGrid" onSubmit={add}>{['vendor','category','description','amount'].map(k=><input key={k} type={k==='amount'?'number':'text'} step=".01" placeholder={k[0].toUpperCase()+k.slice(1)} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})} required/>)}<button className="primary">Add expense</button></form></div><div className="panel tableWrap"><table><thead><tr><th>Date</th><th>Vendor</th><th>Category</th><th>Description</th><th>Amount</th></tr></thead><tbody>{expenses.map(e=><tr key={e.id}><td>{e.expense_date}</td><td>{e.vendor}</td><td>{e.category}</td><td>{e.description}</td><td>{money(e.amount)}</td></tr>)}</tbody></table></div></>}
createRoot(document.getElementById('root')).render(<App/>);
